# Generated by Django 5.2.11 on 2026-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('unit', 'unité(s)'), ('cs', 'c. à s.'), ('cc', 'c. à c.'), ('pincee', 'pincée')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('unit', 'unité(s)'), ('cs', 'c. à s.'), ('cc', 'c. à c.'), ('pincee', 'pincée')], max_length=30),
        ),
    ]
