# Generated by Django 5.2.11 on 2026-02-13 08:35

import django.db.models.deletion
from django.db import migrations, models


FALLBACK_INGREDIENT_NAME = 'Ingrédient sans nom'


def migrate_shared_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('core', 'Ingredient')
    RecipeIngredient = apps.get_model('core', 'RecipeIngredient')
    ShoppingListItem = apps.get_model('core', 'ShoppingListItem')

    cache = {}

    def get_or_create_ingredient(raw_name):
        normalized_name = (raw_name or '').strip()
        if not normalized_name:
            normalized_name = FALLBACK_INGREDIENT_NAME

        cache_key = normalized_name.lower()
        ingredient = cache.get(cache_key)
        if ingredient is not None:
            return ingredient

        ingredient = Ingredient.objects.filter(name__iexact=normalized_name).first()
        if ingredient is None:
            ingredient = Ingredient.objects.create(name=normalized_name)

        cache[cache_key] = ingredient
        return ingredient

    for recipe_ingredient in RecipeIngredient.objects.all().iterator():
        ingredient = get_or_create_ingredient(recipe_ingredient.name)
        RecipeIngredient.objects.filter(pk=recipe_ingredient.pk).update(ingredient_id=ingredient.pk)

    for item in ShoppingListItem.objects.all().iterator():
        ingredient = get_or_create_ingredient(item.name)
        ShoppingListItem.objects.filter(pk=item.pk).update(
            ingredient_id=ingredient.pk,
            name=ingredient.name,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipeingredient_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recipe_usages',
                to='core.ingredient',
            ),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='ingredient',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shopping_list_items',
                to='core.ingredient',
            ),
        ),
        migrations.RunPython(migrate_shared_ingredients, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['ingredient__name']},
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recipe_usages',
                to='core.ingredient',
            ),
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
    ]
